name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  lottie: ^2.5.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  csv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/vpn/
    - assets/lottie/